server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendationfitness
      database: airecommendationfitness
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.models.Activity
        spring.json.trusted.packages: "*"
#        max:
#          poll:
#            interval:
#              ms: 600000  # 10 minutes

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

kafka:
  topic:
    name: activity-events

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      fitness:
        aiservice: DEBUG
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG